name: Deploy Server

on:
  push:
    branches: [ main ]
    paths:
      - 'server/**'
      - 'shared/**'
      - '.github/workflows/deploy-server.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      
      - name: Deploy to Cloud Run
        run: |
          cd server
          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/dailyfortune-api
          gcloud run deploy dailyfortune-api \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/dailyfortune-api \
            --platform managed \
            --region asia-northeast1 \
            --allow-unauthenticated \
            --set-env-vars="NODE_ENV=production,MONGODB_URI=${{ secrets.MONGODB_URI }},CLIENT_URL=https://dailyfortune.web.app,ADMIN_URL=https://dailyfortune-admin.web.app" \
            --set-secrets="FIREBASE_SERVICE_ACCOUNT=firebase-admin-sdk:latest,JWT_SECRET=jwt-secret:latest"